
import os

# API PEDIDOS com validacao de estoque
api = ''
api += 'import { NextRequest, NextResponse } from ' + chr(34) + 'next/server' + chr(34) + ';\n'
api += 'import { prisma } from ' + chr(34) + '@/lib/prisma' + chr(34) + ';\n\n'
api += 'export async function POST(req: NextRequest) {\n'
api += '  const { clienteNome, clienteTelefone, observacoes, itens } = await req.json();\n'
api += '  if (!clienteNome || !clienteTelefone || !itens?.length)\n'
api += '    return NextResponse.json({ error: ' + chr(34) + 'Dados incompletos' + chr(34) + ' }, { status: 400 });\n\n'
api += '  // Valida estoque de todos os itens antes de criar o pedido\n'
api += '  for (const item of itens) {\n'
api += '    const produto = await prisma.produto.findUnique({ where: { id: item.produtoId } });\n'
api += '    if (!produto) return NextResponse.json({ error: ' + chr(34) + 'Produto nao encontrado' + chr(34) + ' }, { status: 404 });\n'
api += '    if (produto.estoque < item.quantidade)\n'
api += '      return NextResponse.json({ error: ' + chr(34) + 'Estoque insuficiente para ' + chr(34) + ' + produto.nome + ' + chr(34) + '. Disponivel: ' + chr(34) + ' + produto.estoque }, { status: 409 });\n'
api += '  }\n\n'
api += '  const cliente = await prisma.cliente.upsert({\n'
api += '    where: { telefone: clienteTelefone },\n'
api += '    update: { nome: clienteNome },\n'
api += '    create: { nome: clienteNome, telefone: clienteTelefone },\n'
api += '  });\n\n'
api += '  const total = itens.reduce((acc: number, i: any) => acc + i.precoUnitario * i.quantidade, 0);\n\n'
api += '  // Cria pedido e desconta estoque em transacao atomica\n'
api += '  const pedido = await prisma.(async (tx) => {\n'
api += '    const p = await tx.pedido.create({\n'
api += '      data: {\n'
api += '        clienteId: cliente.id,\n'
api += '        total,\n'
api += '        observacoes,\n'
api += '        itens: {\n'
api += '          create: itens.map((i: any) => ({\n'
api += '            produtoId: i.produtoId,\n'
api += '            quantidade: i.quantidade,\n'
api += '            precoUnitario: i.precoUnitario,\n'
api += '          })),\n'
api += '        },\n'
api += '      },\n'
api += '      include: { itens: true },\n'
api += '    });\n'
api += '    // Desconta estoque de cada produto\n'
api += '    for (const item of itens) {\n'
api += '      await tx.produto.update({\n'
api += '        where: { id: item.produtoId },\n'
api += '        data: { estoque: { decrement: item.quantidade } },\n'
api += '      });\n'
api += '    }\n'
api += '    return p;\n'
api += '  });\n\n'
api += '  return NextResponse.json(pedido);\n'
api += '}\n\n'
api += 'export async function GET() {\n'
api += '  const pedidos = await prisma.pedido.findMany({\n'
api += '    orderBy: { criadoEm: ' + chr(34) + 'desc' + chr(34) + ' },\n'
api += '    include: { cliente: true, itens: { include: { produto: true } } },\n'
api += '  });\n'
api += '  return NextResponse.json(pedidos);\n'
api += '}\n'

with open('src/app/api/pedidos/route.ts', 'w', encoding='utf-8', newline='\n') as f:
    f.write(api)
print('API PEDIDOS OK')
