
q = chr(34)
content = q + 'use client' + q + ';\n\n'
content += 'import { useState } from ' + q + 'react' + q + ';\n'
content += 'import { useCarrinho } from ' + q + '@/hooks/useCarrinho' + q + ';\n'
content += 'import TabCardapio from ' + q + '@/components/cliente/TabCardapio' + q + ';\n'
content += 'import TabPedido from ' + q + '@/components/cliente/TabPedido' + q + ';\n'
content += 'import TabConta from ' + q + '@/components/cliente/TabConta' + q + ';\n'
content += 'import TabInfo from ' + q + '@/components/cliente/TabInfo' + q + ';\n\n'
content += 'type Aba = ' + q + 'cardapio' + q + ' | ' + q + 'pedido' + q + ' | ' + q + 'conta' + q + ' | ' + q + 'info' + q + ';\n\n'
content += 'export default function Home() {\n'
content += '  const [aba, setAba] = useState<Aba>(' + q + 'cardapio' + q + ');\n'
content += '  const { itens } = useCarrinho();\n'
content += '  const totalItens = itens.reduce((acc, i) => acc + i.quantidade, 0);\n\n'
content += '  return (\n'
content += '    <div>\n'
content += '      <header className=' + q + 'app-header' + q + '>\n'
content += '        <h1>Claudia Cakes</h1>\n'
content += '        <p>Bolos, tortas e salgados artesanais</p>\n'
content += '      </header>\n'
content += '      <nav className=' + q + 'tabs-nav' + q + '>\n'
content += '        <button className={aba === ' + q + 'cardapio' + q + ' ? ' + q + 'ativa' + q + ' : ' + q + q + '} onClick={() => setAba(' + q + 'cardapio' + q + ')}>\n'
content += '          <span className=' + q + 'tab-icone' + q + '>??</span>Cardapio\n'
content += '        </button>\n'
content += '        <button className={aba === ' + q + 'pedido' + q + ' ? ' + q + 'ativa' + q + ' : ' + q + q + '} onClick={() => setAba(' + q + 'pedido' + q + ')}>\n'
content += '          <span className=' + q + 'tab-icone' + q + '>?? {totalItens > 0 && <span className=' + q + 'badge' + q + '>{totalItens}</span>}</span>Pedido\n'
content += '        </button>\n'
content += '        <button className={aba === ' + q + 'conta' + q + ' ? ' + q + 'ativa' + q + ' : ' + q + q + '} onClick={() => setAba(' + q + 'conta' + q + ')}>\n'
content += '          <span className=' + q + 'tab-icone' + q + '>??</span>Minha Conta\n'
content += '        </button>\n'
content += '        <button className={aba === ' + q + 'info' + q + ' ? ' + q + 'ativa' + q + ' : ' + q + q + '} onClick={() => setAba(' + q + 'info' + q + ')}>\n'
content += '          <span className=' + q + 'tab-icone' + q + '>??</span>Info\n'
content += '        </button>\n'
content += '      </nav>\n'
content += '      <main className=' + q + 'tab-conteudo' + q + '>\n'
content += '        {aba === ' + q + 'cardapio' + q + ' && <TabCardapio onAdicionado={() => setAba(' + q + 'pedido' + q + ')} />}\n'
content += '        {aba === ' + q + 'pedido' + q + ' && <TabPedido onIrParaConta={() => setAba(' + q + 'conta' + q + ')} />}\n'
content += '        {aba === ' + q + 'conta' + q + ' && <TabConta />}\n'
content += '        {aba === ' + q + 'info' + q + ' && <TabInfo />}\n'
content += '      </main>\n'
content += '    </div>\n'
content += '  );\n'
content += '}\n'

with open('src/app/page.tsx', 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

print('page OK')
